### ISSUE TITLE
An error related to auto-scaling?

### ISSUE THREAD

**Issue by byouloh** [google/cluster-insight#126]
When all pods are Running state, cluster-insight is doing well. But, when I use auto-scaling and so pods are as belows:

homepage      auto-580846070-qzf7s                    1/2       ErrImagePull       0          39s
homepage      scouter-2016285154-kdz9x                1/1       Running            0          1d
homepage      test-621478404-w1fsx                    1/2       CrashLoopBackOff   6          20m

cluster-insight shows the following errors:

10.32.0.1 - - [19/Jun/2017 06:31:16] "GET /cluster HTTP/1.1" 500 -
10.32.0.1 - - [19/Jun/2017 06:31:25] "GET /cluster HTTP/1.1" 500 -
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
10.32.0.1 - - [19/Jun/2017 06:33:10] "GET /cluster/resources/pods HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
10.32.0.1 - - [19/Jun/2017 06:33:11] "GET /cluster/resources/pods HTTP/1.1" 200 -
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
10.32.0.1 - - [19/Jun/2017 06:33:23] "GET /cluster/resources HTTP/1.1" 500 -
10.32.0.1 - - [19/Jun/2017 06:33:23] "GET /cluster/resources HTTP/1.1" 500 -
10.32.0.1 - - [19/Jun/2017 06:33:23] "GET /cluster HTTP/1.1" 500 -
10.32.0.1 - - [19/Jun/2017 06:33:23] "GET /cluster HTTP/1.1" 500 -

When I don't use auto-scaling and some pods are not Running state, cluster-insight are working well. So I think that the error is strongly related to auto-scaling functionality.

Could anyone help me?

**Comment by byouloh** [comment]
When the status of a pod is "ImagePullBackOff", the imageID of the pod is empty, "". So, this makes an error, exactly to say "assert": the 138th line of ./collector/utilities.py.

You can make that line an comment mark and use cluster-insight without any error related to this temporarily. But it should be fixed in long term.
