### ISSUE TITLE
get_images() fails with KeyError

### ISSUE THREAD

**Issue by EranGabber** [google/cluster-insight#33]
The cluster-insight collector at http://104.154.64.24:5555/  fails with the following messages:

/cluster/resources/images fails with this message:
{
  "error_message": "kubernetes.get_images() failed with exception <type 'exceptions.KeyError'>", 
  "success": false, 
  "timestamp": "2015-04-06T18:53:09.078006"
}
/cluster fails with this message:
{
  "error_message": "\"calling <function _do_compute_node at 0x7fc04513f320> with arguments {'node': {'id': u'kubernetes-minion-ni4v.c.the-pentameter-90318.internal', 'timestamp': '2015-04-06T18:44:46.451123', 'type': 'Node', 'properties': {u'status': {u'nodeInfo': {u'systemUUID': u'FF43C485-F704-7C0F-2F05-D5216E5B148A', u'machineID': u''}, u'conditions': [{u'status': u'Full', u'lastTransitionTime': u'2015-04-02T18:41:16Z', u'kind': u'Ready', u'lastProbeTime': u'2015-04-06T18:44:45Z', u'reason': u'kubelet is posting ready status'}], u'addresses': [{u'type': u'ExternalIP', u'address': u'104.154.64.24'}, {u'type': u'LegacyHostIP', u'address': u'104.197.30.200'}]}, u'uid': u'd89ea1c1-d967-11e4-bd90-42010af0f42f', u'resourceVersion': 710317, u'externalID': u'2709906458529347936', u'resources': {u'capacity': {u'cpu': u'1', u'memory': 3892043776}}, u'hostIP': u'104.197.30.200', u'creationTimestamp': u'2015-04-02T18:41:16Z', u'id': u'kubernetes-minion-ni4v.c.the-pentameter-90318.internal', u'selfLink': u'/api/v1beta1/nodes/kubernetes-minion-ni4v.c.the-pentameter-90318.internal'}, 'annotations': {'label': u'kubernetes-minion-ni4v'}}, 'cluster_guid': u'Cluster:the-pentameter-90318', 'gs': <global_state.GlobalState object at 0x7fc04513c890>, 'g': <context.ContextGraph object at 0x7fc04410bb90>, 'input_queue': <Queue.PriorityQueue instance at 0x7fc044172d88>} failed with exception <type 'exceptions.KeyError'>\"", 
  "success": false, 
  "timestamp": "2015-04-06T18:51:24.083677"
}

**Comment by EranGabber** [comment]
The failure occurred in line 160 of get_pods():
Traceback (most recent call last):
  File "./collector.py", line 251, in get_images
    images_list.extend(docker.get_images(gs, node['id']))
  File "/usr/src/app/utilities.py", line 83, in inner
    return func(arg1, arg2)
  File "/usr/src/app/docker.py", line 494, in get_images
    for pod in kubernetes.get_pods(gs, docker_host):
  File "/usr/src/app/utilities.py", line 105, in inner
    return func(arg1, arg2)
  File "/usr/src/app/kubernetes.py", line 160, in get_pods
    if pod['currentState']['host'] == node_id:
KeyError: 'host'


I found one pod in a waiting state which does not have a host.

{
      "annotations": {
        "label": "cassandra-kqj6r"
      }, 
      "id": "cassandra-kqj6r", 
      "properties": {
        "creationTimestamp": "2015-04-06T15:45:47Z", 
        "currentState": {
          "manifest": {
            "containers": null, 
            "id": "", 
            "restartPolicy": {}, 
            "version": "", 
            "volumes": null
          }, 
          "status": "Waiting"
        }, 
        "desiredState": {
          "manifest": {
            "containers": [
              {
                "capabilities": {}, 
                "command": [
                  "/run.sh"
                ], 
                "cpu": 1000, 
                "env": [
                  {
                    "key": "MAX_HEAP_SIZE", 
                    "name": "MAX_HEAP_SIZE", 
                    "value": "512M"
                  }, 
                  {
                    "key": "HEAP_NEWSIZE", 
                    "name": "HEAP_NEWSIZE", 
                    "value": "100M"
                  }
                ], 
                "image": "kubernetes/cassandra:v2", 
                "imagePullPolicy": "PullIfNotPresent", 
                "name": "cassandra", 
                "ports": [
                  {
                    "containerPort": 9042, 
                    "name": "cql", 
                    "protocol": "TCP"
                  }, 
                  {
                    "containerPort": 9160, 
                    "name": "thrift", 
                    "protocol": "TCP"
                  }
                ], 
                "resources": {
                  "limits": {
                    "cpu": "1"
                  }
                }, 
                "terminationMessagePath": "/dev/termination-log", 
                "volumeMounts": [
                  {
                    "mountPath": "/cassandra_data", 
                    "name": "data", 
                    "path": "/cassandra_data"
                  }
                ]
              }
            ], 
            "dnsPolicy": "ClusterFirst", 
            "id": "", 
            "restartPolicy": {
              "always": {}
            }, 
            "version": "v1beta2", 
            "volumes": [
              {
                "name": "data", 
                "source": {
                  "emptyDir": {
                    "medium": ""
                  }, 
                  "gitRepo": null, 
                  "hostDir": null, 
                  "nfs": null, 
                  "persistentDisk": null, 
                  "secret": null
                }
              }
            ]
          }
        }, 
        "generateName": "cassandra-", 
        "id": "cassandra-kqj6r", 
        "labels": {
          "name": "cassandra"
        }, 
        "namespace": "default", 
        "resourceVersion": 683766, 
        "selfLink": "/api/v1beta1/pods/cassandra-kqj6r?namespace=default", 
        "uid": "fe7622f0-dc73-11e4-bd90-42010af0f42f"
      }, 
      "timestamp": "2015-04-06T20:28:11.417748", 
      "type": "Pod"
    },

**Comment by EranGabber** [comment]
Closed by https://github.com/google/cluster-insight/pull/32.
